version: '3'                                                                                                                                                                                                                                 

services:                                                                                                                                                                                                                                    
  app:
    build: ./src
    environment:
      - "DISPLAY"
    image: comparateur-chaussures-master:latest
#    links:
#      - localhost:db
    network_mode: "host"
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority

    ports:
      - "3306:3306"

  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: "123"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "wadii"
    image: mysql:latest
    network_mode: "host"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
